# -*- coding: utf-8 -*-
"""dataScienceHW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v360tjnzKcTemAqyXqrK-U_UEKRoqOf4

#[google colab連結](https://colab.research.google.com/drive/1v360tjnzKcTemAqyXqrK-U_UEKRoqOf4)

#腦中風人數
"""

#採用政府公開資料-腦中風病人住院日起一百八十日內之平均住院日數(包含住院期間及急性後期照護)
import pandas as pd
brain_stroke = pd.read_excel("腦中風人數.xlsx")
brain_stroke.head()

#更換欄名
col_names = ["year", "hosp_code", "hosp_name", "hosp_type", "case", "surgery", "be_in_hosp", "區域指標值", "全國指標值", "city", "village"]
brain_stroke.columns = col_names
brain_stroke.head()

brain_stroke.shape

#有多少時間點
brain_stroke["year"].unique()

brain_stroke["city"].unique()

#取出台北市資料
is_taipei = brain_stroke["city"] == "臺北市"
is_center = brain_stroke["hosp_type"] == "醫學中心"
is_year = brain_stroke["year"] == "107年第一季"
taipei_per_season = brain_stroke[is_taipei]
taipei_per_season.tail()

grouped = taipei_per_season.groupby("year")
case_counts_ser = grouped["case"].sum().sort_values(ascending=False)
case_counts_ser.index

case_counts_ser.values

import matplotlib.pyplot as plt
continent_cnts = len(case_counts_ser.values)
plt.bar(range(continent_cnts), case_counts_ser.values, color="#f08080")
plt.xticks(range(continent_cnts), case_counts_ser.index)
plt.title("How many cases are there in Taipei every season?")
plt.xlabel("season")
plt.ylabel("case counts")
plt.rcParams['font.sans-serif']=['SimHei']
plt.show()
#matplotlib中文無法顯示

#取出107年第一季資料
year107_s1 = brain_stroke[is_year]
year107_s1.head()

groupbe2 = year107_s1.groupby("city")
case_sum_city = groupbe2["case"].sum().sort_values(ascending=False)
case_sum_city.index

case_sum_city.values

"""##107年各縣市腦中風案例"""

import matplotlib.pyplot as plt
amount = len(case_sum_city.values)
plt.bar(range(amount), case_sum_city.values, color="#ffa500")
plt.xticks(range(amount), case_sum_city.index)
plt.title("How many cases are there in every city 107season?")
plt.xlabel("city")
plt.ylabel("case counts")
plt.show()
#matplotlib中文無法顯示

hex_colors = ["#0084ff", "#44bec7", "#ffc300", "#fa3c4c", "#d696bb"]
city = brain_stroke["city"].unique()

"""##各縣市住院數與手術數關係"""

#各縣市住院數與手術數關係
for col, place in zip(hex_colors, city):
  subset_df = brain_stroke[brain_stroke["city"] == place]
  plt.scatter(subset_df["be_in_hosp"], subset_df["surgery"], color=col, alpha=0.4, label=city)
plt.show()
#中文無法呈現

"""#lung cancer"""

import pandas as pd
lung_cancer = pd.read_excel("lung cancer new.xlsx")
lung_cancer.head()

lung_cancer["city"].unique()

lung_cancer["year"].unique()

groupbeYear = lung_cancer.groupby("year")
cancer_year_ser = groupbeYear["cancer"].sum().sort_values(ascending=False)
cancer_year_ser.index

cancer_year_ser.values

#每年平均吸菸率
smoking_year_ser = groupbeYear["smoking rate"].mean().sort_values(ascending=False)
smoking_year_ser.index

smoking_year_ser.values

"""##歷年肺癌人數"""

#歷年肺癌人數
plt.plot(cancer_year_ser.index,cancer_year_ser.values, label = "lung cancer amount")
plt.legend()
plt.show()

groupbe_city = lung_cancer.groupby("city")
city_ser = groupbe_city["cancer"].sum().sort_values(ascending=False)
city_ser.index

city_ser.values

"""##各縣市肺癌總數"""

figure, axis = plt.subplots(figsize=(29, 5))
amount_each_city = len(city_ser.values)
plt.bar(range(amount_each_city), city_ser.values, color="#40e0d0")
plt.xticks(range(amount_each_city), city_ser.index)
plt.title("How many lung cancer are there in each city?")
plt.xlabel("city")
plt.ylabel("lung cancer amount")
plt.show()

