# -*- coding: utf-8 -*-
"""final report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o5dmCvf8m9tiNqocEndKWQQkEwo9_N4J

#縣市2011-2015肺癌相關資料
"""

import matplotlib.pyplot as plt
import pandas as pd
cancer = pd.read_excel("data for report.xlsx")
cancer.head()

cancer["city"].unique()

cancer["year"].unique()

groupbeYear = cancer.groupby("year")
cancer_year_ser = groupbeYear["cancer"].sum()
cancer_year_ser.index

cancer_year_ser.values

smoking_year_ser = groupbeYear["smoking rate"].mean()
smoking_year_ser.index
smoking_year_ser.values

"""##歷年肺癌人數與吸菸率關係
觀察近年肺癌人數逐漸上升，，吸菸被列為最有可能罹患肺癌的原因，希望透過下列方式確認肺癌與吸菸之關係是否為正相關？
"""

fig = plt.figure()
can = fig.add_subplot(111)
can.plot(cancer_year_ser.index, cancer_year_ser.values ,label = "lung cancer amount", color="#f6546a")
smoking = can.twinx()
smoking.plot(smoking_year_ser.index, smoking_year_ser.values, label = "smoking rate")
can.set_xlabel("year")
can.set_ylabel("lung cancer amount")
smoking.set_ylabel("smoking rate")
plt.title("Relationship between smoking rate and lung cancer")
can.legend()
smoking.legend()
plt.legend()
plt.show()

"""由上圖可知，歷年肺癌人數與吸菸率呈負向關係。`

##各縣市歷年罹患肺癌人數
因此想檢視哪一個縣市罹患肺癌人數最多
"""

figure, axis = plt.subplots(figsize=(29, 5))
amount_each_city = len(city_ser.values)
plt.bar(range(amount_each_city), city_ser.values, color="#40e0d0")
plt.xticks(range(amount_each_city), city_ser.index)
plt.title("How many lung cancer are there in each city?")
plt.xlabel("city")
plt.ylabel("lung cancer amount")
plt.show()

"""發現新北市累計罹患肺癌人數最多

#腦中風人數
腦中風是國人十大死因的第二名，僅次於癌症。
男性與女性分別於45與55歲以後罹患腦中風的風險就會增加
"""

import pandas as pd
import matplotlib.pyplot as plt
brain_stroke = pd.read_excel("腦中風人數.xlsx")
brain_stroke.head()

#更換欄名
col_names = ["year", "hosp_code", "hosp_name", "hosp_type", "case", "surgery", "be_in_hosp", "區域指標值", "全國指標值", "city", "village"]
brain_stroke.columns = col_names
brain_stroke.head()

brain_stroke["year"].unique()

brain_stroke["city"].unique()

#取出台北市資料
is_taipei = brain_stroke["city"] == "Taipei City"
is_center = brain_stroke["hosp_type"] == "醫學中心"
is_year = brain_stroke["year"] == 10701
taipei_per_season = brain_stroke[is_taipei]
taipei_per_season.tail()

grouped = taipei_per_season.groupby("year")
case_counts_ser = grouped["case"].sum()
case_counts_ser.index

grouped = brain_stroke.groupby("year")
case_counts_ser = grouped["case"].sum()
case_counts_ser.index
case_counts_ser.values

"""##歷年每季腦中風人數

天氣變化，氣溫急速下降是一種外來的壓力，會改變心臟血管收縮狀態，增加心臟負荷，導致心肌缺氧變化，因而引發心肌梗塞。高血壓、心血管疾病老人常容易發生腦中風。，因此想知道季節是否與腦中風人數有關？
"""

import matplotlib.pyplot as plt
figure, axis = plt.subplots(figsize=(15, 5))
continent_cnts = len(case_counts_ser.values)
plt.bar(range(continent_cnts), case_counts_ser.values, color="#f08080")
plt.xticks(range(continent_cnts), case_counts_ser.index)
plt.title("How many cases in every season?")
plt.xlabel("season")
plt.ylabel("case counts")
plt.show()

"""冬季並無較其他季節有更高的發生次數"""

year107_s1 = brain_stroke[is_year]
year107_s1.head()

groupbe2 = year107_s1.groupby("city")
case_sum_city = groupbe2["case"].sum().sort_values(ascending=False)
case_sum_city.index

case_sum_city.values

"""##107年第一季各縣市case數
想知道各地區腦中風人數是相差甚大？
"""

import matplotlib.pyplot as plt
amount = len(case_sum_city.values)
figure, axis = plt.subplots(figsize=(29, 5))
plt.bar(range(amount), case_sum_city.values, color="#ffa500")
plt.xticks(range(amount), case_sum_city.index)
plt.title("How many cases are there in every city 107season?")
plt.xlabel("city")
plt.ylabel("case counts")

plt.show()

"""##發生案例數與手術數之關聯

耳聞腦中風於將來生活有很大的影響，需要手術治療，因此好奇發生案例與需要手術是否有很大的關聯？
"""

plt.scatter(city_total["case"].sum(), city_total["surgery"].sum(), color="#ccff00")
plt.title("The relationship between surgery and case")
plt.xlabel("case")
plt.ylabel("surgery")

